# Generated by Django 4.2.30 on 2026-05-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='estimated_saving',
            field=models.FloatField(default=0.0, help_text='Estimated saving in GBP per month'),
        ),
    ]
