# Generated by Django 4.2.30 on 2026-05-18 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appliances', '0002_appliance_last_turned_on_at'),
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_minutes', models.FloatField()),
                ('usage_kwh', models.FloatField()),
                ('estimated_cost', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='appliances.appliance')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField()),
                ('total_kwh', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bill_date'],
                'unique_together': {('homeowner', 'bill_date')},
            },
        ),
    ]
