# Generated by Django 4.2.30 on 2026-05-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='last_turned_on_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
